version: "3.8"

services:
  app:
    build: .
    volumes:
      - vendor:/app/vendor
    ports:
      - "8080:8080"
    environment:
      NULLSTONE_ENV: local
      POSTGRES_URL: postgres://postgres:postgres@db:5432/app
      PORT: 8080
    depends_on:
      - db

  db:
    image: "postgres:15"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app

volumes:
  vendor: {}
